### ISSUE TITLE
关于数据的来源

### ISSUE THREAD

**Issue by ccwss1232** [benzenemo/TightlyCoupledINSGNSS#7]
请问你们是用哪家企业的仪器采集紧耦合的数据的

**Comment by benzenemo** [comment]
实验使用的是 Novatel SPAN设备（型号：PwrPak7D-E1）发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***>日期： 2021年11月15日周一 11:01收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***>抄送： Subscribed ***@***.***>主    题： [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)

请问你们是用哪家企业的仪器采集紧耦合的数据的

**Comment by ccwss1232** [comment]
请问该设备能输出伪距、卫星钟差、大气层误差这些数据吗？还是那种十六进制的原始数据，我最近也在做紧耦合，但是得到的伪距观测值和真实几何距离相差很大，在做误差消除。

**Comment by benzenemo** [comment]
可以输出位伪距相位广播电文，其他的改正项需要自己算，可以看一下卫星导航方面的参考书。发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***>日期： 2021年11月15日周一 11:22收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***>抄送： benzenemo ***@***.***>, Comment ***@***.***>主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)

请问该设备能输出伪距、卫星钟差、大气层误差这些数据吗？还是那种十六进制的原始数据，我最近也在做紧耦合，但是得到的伪距观测值和真实几何距离相差很大，在做误差消除。

**Comment by ccwss1232** [comment]
大佬，方便加下我wx吗？sjj1102165192

**Comment by benzenemo** [comment]
有问题直接发邮件就行  我看到了会回复的发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***>日期： 2021年11月15日周一 13:15收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***>抄送： benzenemo ***@***.***>, Comment ***@***.***>主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)

大佬，方便加下我wx吗？sjj1102165192

**Comment by ccwss1232** [comment]
好的，我大致看了下你的数据处理，有一处我不太明白，接收机钟差你是怎么处理的，我看不太懂

**Comment by benzenemo** [comment]
接收机钟差是作为未知数解算的，在状态量里发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***>日期： 2021年11月15日周一 20:01收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***>抄送： benzenemo ***@***.***>, Comment ***@***.***>主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)

好的，我大致看了下你的数据处理，有一处我不太明白，接收机钟差你是怎么处理的，我看不太懂

**Comment by ccwss1232** [comment]
好的，请问这部分的参考文献有吗？我看网上都是用单点估计的方法计算接收机钟差的，那并不准确。

**Comment by benzenemo** [comment]
我用的参考文献在我程序的readme.md里，Paul d Groves那本书，中文版是练军想翻译的，代码主要用了第14章、第8和第9章。我的代码就是基于这本书的代码改的，代码里的公式和书里编号是对应的，很好查到。你可以先看一下，接收机钟差那部分我确实改了不少，看完以后可以再交流。发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***>日期： 2021年11月15日周一 20:08收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***>抄送： benzenemo ***@***.***>, Comment ***@***.***>主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)

好的，请问这部分的参考文献有吗？我看网上都是用单点估计的方法计算接收机钟差的，那并不准确。

**Comment by ccwss1232** [comment]
请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？

**Comment by benzenemo** [comment]
一般都接收机的技术要求是1ms以内发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***>日期： 2021年11月26日周五 16:45收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***>抄送： benzenemo ***@***.***>, Comment ***@***.***>主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)

请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？

**Comment by ccwss1232** [comment]
你的数据我看了下接收机钟差都只在几米而已



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: benzenemo ***@***.***&gt;
发送时间: 2021年11月26日 16:54
收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;
抄送: ccwss1232 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)





 一般都接收机的技术要求是1ms以内发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&gt;日期： 2021年11月26日周五 16:45收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;抄送： benzenemo ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 
 请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？ 
 
 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benzenemo** [comment]
这个确实不同接收机的差别比较大发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***>日期： 2021年11月26日周五 16:57收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***>抄送： benzenemo ***@***.***>, Comment ***@***.***>主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)
你的数据我看了下接收机钟差都只在几米而已







发自我的iPhone





------------------ 原始邮件 ------------------

发件人: benzenemo ***@***.***&gt;

发送时间: 2021年11月26日 16:54

收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;

抄送: ccwss1232 ***@***.***&gt;, Author ***@***.***&gt;

主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)











 一般都接收机的技术要求是1ms以内发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&gt;日期： 2021年11月26日周五 16:45收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;抄送： benzenemo ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 

 请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？ 

 

 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ccwss1232** [comment]
我们的数据问题很大，请问你那边还有其他数据吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: benzenemo ***@***.***&gt;
发送时间: 2021年11月26日 17:00
收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;
抄送: ccwss1232 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)





 这个确实不同接收机的差别比较大发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&gt;日期： 2021年11月26日周五 16:57收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;抄送： benzenemo ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 
 你的数据我看了下接收机钟差都只在几米而已 
 
 
 
 
 
 
 
 发自我的iPhone 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 
 发件人: benzenemo ***@***.***&amp;gt; 
 
 发送时间: 2021年11月26日 16:54 
 
 收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt; 
 
 抄送: ccwss1232 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 
 主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 
 
 
 
 
 
 
 
 
 
 
 
  一般都接收机的技术要求是1ms以内发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;gt;日期： 2021年11月26日周五 16:45收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt;抄送： benzenemo ***@***.***&amp;gt;, Comment ***@***.***&amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)  
 
  请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？  
 
   
 
  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  
 
 — 
 
 You are receiving this because you authored the thread. 
 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benzenemo** [comment]
我这边都是这台接收机的，没有其他设备的。发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***>日期： 2021年11月26日周五 17:11收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***>抄送： benzenemo ***@***.***>, Comment ***@***.***>主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)
我们的数据问题很大，请问你那边还有其他数据吗







发自我的iPhone





------------------ 原始邮件 ------------------

发件人: benzenemo ***@***.***&gt;

发送时间: 2021年11月26日 17:00

收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;

抄送: ccwss1232 ***@***.***&gt;, Author ***@***.***&gt;

主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)











 这个确实不同接收机的差别比较大发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&gt;日期： 2021年11月26日周五 16:57收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;抄送： benzenemo ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 

 你的数据我看了下接收机钟差都只在几米而已 

 

 

 

 

 

 

 

 发自我的iPhone 

 

 

 

 

 

 ------------------ 原始邮件 ------------------ 

 

 发件人: benzenemo ***@***.***&amp;gt; 

 

 发送时间: 2021年11月26日 16:54 

 

 收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt; 

 

 抄送: ccwss1232 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 

 

 主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 

 

 

 

 

 

 

 

 

 

 

 

  一般都接收机的技术要求是1ms以内发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;gt;日期： 2021年11月26日周五 16:45收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt;抄送： benzenemo ***@***.***&amp;gt;, Comment ***@***.***&amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)  

 

  请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？  

 

   

 

  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  

 

 — 

 

 You are receiving this because you authored the thread. 

 

 Reply to this email directly, view it on GitHub, or unsubscribe. 

 

 Triage notifications on the go with GitHub Mobile for iOS or Android. 

 

 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ccwss1232** [comment]
那你能再发我一些数据吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: benzenemo ***@***.***&gt;
发送时间: 2021年11月26日 17:21
收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;
抄送: ccwss1232 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)





 我这边都是这台接收机的，没有其他设备的。发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&gt;日期： 2021年11月26日周五 17:11收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;抄送： benzenemo ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 
 我们的数据问题很大，请问你那边还有其他数据吗 
 
 
 
 
 
 
 
 发自我的iPhone 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 
 发件人: benzenemo ***@***.***&amp;gt; 
 
 发送时间: 2021年11月26日 17:00 
 
 收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt; 
 
 抄送: ccwss1232 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 
 主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 
 
 
 
 
 
 
 
 
 
 
 
  这个确实不同接收机的差别比较大发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;gt;日期： 2021年11月26日周五 16:57收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt;抄送： benzenemo ***@***.***&amp;gt;, Comment ***@***.***&amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)  
 
  你的数据我看了下接收机钟差都只在几米而已  
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
  发自我的iPhone  
 
   
 
   
 
   
 
   
 
   
 
  ------------------ 原始邮件 ------------------  
 
   
 
  发件人: benzenemo ***@***.***&amp;amp;gt;  
 
   
 
  发送时间: 2021年11月26日 16:54  
 
   
 
  收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;amp;gt;  
 
   
 
  抄送: ccwss1232 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
 
   
 
  主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)  
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   一般都接收机的技术要求是1ms以内发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;amp;gt;日期： 2021年11月26日周五 16:45收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;amp;gt;抄送： benzenemo ***@***.***&amp;amp;gt;, Comment ***@***.***&amp;amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)   
 
   
 
   请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？   
 
   
 
     
 
   
 
   —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.   
 
   
 
  —  
 
   
 
  You are receiving this because you authored the thread.  
 
   
 
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 
   
 
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 
   
 
  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  
 
 — 
 
 You are receiving this because you authored the thread. 
 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benzenemo** [comment]
现有的这个不不够么？因为我之前的数据是在学校呀做的，现在工作都好几年了，不太好找了发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***>日期： 2021年11月26日周五 17:24收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***>抄送： benzenemo ***@***.***>, Comment ***@***.***>主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)
那你能再发我一些数据吗







发自我的iPhone





------------------ 原始邮件 ------------------

发件人: benzenemo ***@***.***&gt;

发送时间: 2021年11月26日 17:21

收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;

抄送: ccwss1232 ***@***.***&gt;, Author ***@***.***&gt;

主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)











 我这边都是这台接收机的，没有其他设备的。发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&gt;日期： 2021年11月26日周五 17:11收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;抄送： benzenemo ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 

 我们的数据问题很大，请问你那边还有其他数据吗 

 

 

 

 

 

 

 

 发自我的iPhone 

 

 

 

 

 

 ------------------ 原始邮件 ------------------ 

 

 发件人: benzenemo ***@***.***&amp;gt; 

 

 发送时间: 2021年11月26日 17:00 

 

 收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt; 

 

 抄送: ccwss1232 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 

 

 主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 

 

 

 

 

 

 

 

 

 

 

 

  这个确实不同接收机的差别比较大发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;gt;日期： 2021年11月26日周五 16:57收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt;抄送： benzenemo ***@***.***&amp;gt;, Comment ***@***.***&amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)  

 

  你的数据我看了下接收机钟差都只在几米而已  

 

   

 

   

 

   

 

   

 

   

 

   

 

   

 

  发自我的iPhone  

 

   

 

   

 

   

 

   

 

   

 

  ------------------ 原始邮件 ------------------  

 

   

 

  发件人: benzenemo ***@***.***&amp;amp;gt;  

 

   

 

  发送时间: 2021年11月26日 16:54  

 

   

 

  收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;amp;gt;  

 

   

 

  抄送: ccwss1232 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  

 

   

 

  主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)  

 

   

 

   

 

   

 

   

 

   

 

   

 

   

 

   

 

   

 

   

 

   

 

   一般都接收机的技术要求是1ms以内发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;amp;gt;日期： 2021年11月26日周五 16:45收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;amp;gt;抄送： benzenemo ***@***.***&amp;amp;gt;, Comment ***@***.***&amp;amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)   

 

   

 

   请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？   

 

   

 

     

 

   

 

   —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.   

 

   

 

  —  

 

   

 

  You are receiving this because you authored the thread.  

 

   

 

  Reply to this email directly, view it on GitHub, or unsubscribe.  

 

   

 

  Triage notifications on the go with GitHub Mobile for iOS or Android.  

 

   

 

  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  

 

 — 

 

 You are receiving this because you authored the thread. 

 

 Reply to this email directly, view it on GitHub, or unsubscribe. 

 

 Triage notifications on the go with GitHub Mobile for iOS or Android. 

 

 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ccwss1232** [comment]
好的，那请问您的这个imu数据的坐标系是东北天的吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: benzenemo ***@***.***&gt;
发送时间: 2021年11月26日 17:43
收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;
抄送: ccwss1232 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)





 现有的这个不不够么？因为我之前的数据是在学校呀做的，现在工作都好几年了，不太好找了发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&gt;日期： 2021年11月26日周五 17:24收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;抄送： benzenemo ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 
 那你能再发我一些数据吗 
 
 
 
 
 
 
 
 发自我的iPhone 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 
 发件人: benzenemo ***@***.***&amp;gt; 
 
 发送时间: 2021年11月26日 17:21 
 
 收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt; 
 
 抄送: ccwss1232 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 
 主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 
 
 
 
 
 
 
 
 
 
 
 
  我这边都是这台接收机的，没有其他设备的。发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;gt;日期： 2021年11月26日周五 17:11收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt;抄送： benzenemo ***@***.***&amp;gt;, Comment ***@***.***&amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)  
 
  我们的数据问题很大，请问你那边还有其他数据吗  
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
  发自我的iPhone  
 
   
 
   
 
   
 
   
 
   
 
  ------------------ 原始邮件 ------------------  
 
   
 
  发件人: benzenemo ***@***.***&amp;amp;gt;  
 
   
 
  发送时间: 2021年11月26日 17:00  
 
   
 
  收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;amp;gt;  
 
   
 
  抄送: ccwss1232 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
 
   
 
  主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)  
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   
 
   这个确实不同接收机的差别比较大发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;amp;gt;日期： 2021年11月26日周五 16:57收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;amp;gt;抄送： benzenemo ***@***.***&amp;amp;gt;, Comment ***@***.***&amp;amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)   
 
   
 
   你的数据我看了下接收机钟差都只在几米而已   
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
   发自我的iPhone   
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
   ------------------ 原始邮件 ------------------   
 
   
 
     
 
   
 
   发件人: benzenemo ***@***.***&amp;amp;amp;gt;   
 
   
 
     
 
   
 
   发送时间: 2021年11月26日 16:54   
 
   
 
     
 
   
 
   收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;amp;amp;gt;   
 
   
 
     
 
   
 
   抄送: ccwss1232 ***@***.***&amp;amp;amp;gt;, Author ***@***.***&amp;amp;amp;gt;   
 
   
 
     
 
   
 
   主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)   
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
     
 
   
 
    一般都接收机的技术要求是1ms以内发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;amp;amp;gt;日期： 2021年11月26日周五 16:45收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;amp;amp;gt;抄送： benzenemo ***@***.***&amp;amp;amp;gt;, Comment ***@***.***&amp;amp;amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)    
 
   
 
     
 
   
 
    请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？    
 
   
 
     
 
   
 
       
 
   
 
     
 
   
 
    —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.    
 
   
 
     
 
   
 
   —   
 
   
 
     
 
   
 
   You are receiving this because you authored the thread.   
 
   
 
     
 
   
 
   Reply to this email directly, view it on GitHub, or unsubscribe.   
 
   
 
     
 
   
 
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
 
   
 
     
 
   
 
   —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.   
 
   
 
  —  
 
   
 
  You are receiving this because you authored the thread.  
 
   
 
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 
   
 
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 
   
 
  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  
 
 — 
 
 You are receiving this because you authored the thread. 
 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ccwss1232** [comment]
我们的数据问题很大，请问你那边还有其他数据吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: benzenemo ***@***.***&gt;
发送时间: 2021年11月26日 17:00
收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;
抄送: ccwss1232 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)





 这个确实不同接收机的差别比较大发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&gt;日期： 2021年11月26日周五 16:57收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&gt;抄送： benzenemo ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 
 你的数据我看了下接收机钟差都只在几米而已 
 
 
 
 
 
 
 
 发自我的iPhone 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 
 发件人: benzenemo ***@***.***&amp;gt; 
 
 发送时间: 2021年11月26日 16:54 
 
 收件人: benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt; 
 
 抄送: ccwss1232 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 
 主题: Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7) 
 
 
 
 
 
 
 
 
 
 
 
  一般都接收机的技术要求是1ms以内发自我的荣耀手机-------- 原始邮件 --------发件人： ccwss1232 ***@***.***&amp;gt;日期： 2021年11月26日周五 16:45收件人： benzenemo/TightlyCoupledINSGNSS ***@***.***&amp;gt;抄送： benzenemo ***@***.***&amp;gt;, Comment ***@***.***&amp;gt;主    题： Re: [benzenemo/TightlyCoupledINSGNSS] 关于数据的来源 (Issue #7)  
 
  请问你们伪距观测量和真实的卫星载体距离差了大概多少，我看你们的数据大概在几十米以内。顺便问下，接收机钟差在什么数量级？  
 
   
 
  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  
 
 — 
 
 You are receiving this because you authored the thread. 
 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
 
 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benzenemo** [comment]
imu数据的坐标系在Tightly_coupled_INS_GNSS.m开头部分的数据说明里有
